/*
 * Copyright (c) 2025. David Noha
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package net.netbeing.cheap.tags.model;

/**
 * Indicates how a tag application was created, distinguishing between
 * manual, inferred, and automated tag applications.
 *
 * <p>Tag sources provide provenance tracking:</p>
 * <ul>
 *   <li><b>EXPLICIT</b> - Manually applied by a user or developer. These tags
 *       represent intentional, human-made assertions about data semantics.</li>
 *   <li><b>INFERRED</b> - Derived by system rules or logic based on other metadata.
 *       These tags are automatically applied when certain conditions or patterns
 *       are detected.</li>
 *   <li><b>GENERATED</b> - Created by automated processes such as schema discovery,
 *       data profiling, or machine learning. These tags may require validation
 *       or review.</li>
 * </ul>
 *
 * <p>Source tracking enables filtering, auditing, and trust decisions based on
 * how tags were applied. For example, explicitly-applied tags might be treated
 * with higher confidence than generated tags.</p>
 *
 * @see TagApplication
 */
public enum TagSource
{
    /**
     * Tag was explicitly applied by a user or developer.
     * Represents intentional, manual metadata assertions.
     */
    EXPLICIT,

    /**
     * Tag was inferred by system rules based on other metadata.
     * Represents automated logical deductions about data semantics.
     */
    INFERRED,

    /**
     * Tag was generated by an automated process such as schema discovery
     * or data profiling. May require validation or review.
     */
    GENERATED
}
