# Base configuration for cheap-rest service
server:
  port: 8080

spring:
  application:
    name: cheap-rest

cheap:
  pagination:
    default-page-size: 20
    max-page-size: 100
  aspect-upsert:
    max-batch-size: 1000
