# Docker Compose for cheap-rest with MariaDB
version: '3.8'

services:
  mariadb:
    image: mariadb:11
    container_name: cheap-mariadb
    environment:
      MYSQL_DATABASE: cheap
      MYSQL_USER: cheap_user
      MYSQL_PASSWORD: ${DB_PASSWORD:-changeme}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD:-rootpass}
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

  cheap-rest:
    build:
      context: ..
      dockerfile: cheap-rest/Dockerfile
    container_name: cheap-rest-mariadb
    environment:
      SPRING_PROFILES_ACTIVE: mariadb
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/cheap
      SPRING_DATASOURCE_USERNAME: cheap_user
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-changeme}
    ports:
      - "8080:8080"
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mariadb-data:
