# Docker Compose for cheap-rest with PostgreSQL (default)
version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: cheap-postgres
    environment:
      POSTGRES_DB: cheap
      POSTGRES_USER: cheap_user
      POSTGRES_PASSWORD: ${DB_PASSWORD:-changeme}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cheap_user -d cheap"]
      interval: 10s
      timeout: 5s
      retries: 5

  cheap-rest:
    build:
      context: ..
      dockerfile: cheap-rest/Dockerfile
    container_name: cheap-rest
    environment:
      SPRING_PROFILES_ACTIVE: postgres
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cheap
      SPRING_DATASOURCE_USERNAME: cheap_user
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-changeme}
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres-data:
