#
# For now, rebuild the world on any change.
#
name: Build Cheap Java
on:
  push:
    paths:
      - "java/cheap-core/**"
      - "java/cheap-json/**"
      - "java/cheap-db/**"
      - "java/*.gradle.kts"
      - "java/gradle/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '24'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      # When cheap-core changes, rebuild everything
      - name: Run gradle build
        run: ./gradlew build
        working-directory: ./java

      - uses: actions/upload-artifact@v4
        with:
          path: |
            java/*/build/libs/*.jar
            java/*/build/reports/
            java/*/build/test-results/
